### ISSUE TITLE
Create list of mailing lists/comms channels/Slack Groups with relevant events

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/research-application-management#1]
### Summary

* @harisood suggested creating a list of lists for good newsletters/comms channels/Slack Groups for RAMs and others interested in similar topics to join

### What needs to be done?

- [ ] Create file in RAM repo
- [ ] Add content

### Who can help?

* All RAMs
---

### Updates

*

**Comment by aldenc** [comment]
[here](https://github.com/alan-turing-institute/research-application-management/blob/main/onboarding/communities_to_join.md)
