### ISSUE TITLE
Create template for guidance and docs on useful RAM skill areas

### ISSUE THREAD

**Issue by harisood** [alan-turing-institute/research-application-management#14]
### Provide a description

It would be good to standardise/structure how we communicate guidance to different RAM-related activities, e.g. user testing, events, stakeholder mapping. For a starter it should maybe follow:

# Summary
> High level one pager on things for people to consider

# X activity at Turing
> Summary of how to adapt general things above for Turing, e.g. event management speak to events team, can't host huge events etc.

# Case studies
> Examples of these activities that have taken place at Turing (either RAM-led or not)

# Contact

> Generic information on how to get in touch with us for more questions

# Resources
> List of resources for people to deep-dive into

**Comment by harisood** [comment]
@dingaaling putting what we talked about into writing, thoughts?

Also @AidaMehonic @aldenc for thoughts as well!

**Comment by aldenc** [comment]
@harisood do you envision one doc with all this or all these as individual docs? I think we should break this down into the sections and create individual tasks for each one

**Comment by dingaaling** [comment]
@harisood this seems to be captured in our [TTW chapter](https://the-turing-way.netlify.app/collaboration/stakeholder-engagement.html) and some [internal docs](https://github.com/alan-turing-institute/research-application-management/tree/main/docs) 

OK to close this issue?

**Comment by harisood** [comment]
Yep!
