### ISSUE TITLE
Create record of RAM 'research assets'

### ISSUE THREAD

**Issue by harisood** [alan-turing-institute/research-application-management#16]
### Provide a description

In the partnerships call it was mentioned it would be handy to have a record of usable 'research outputs'. Although not discussed in detail, it's easy to see why it would be helpful:
* To showcase Turing's work
* To showcase projects RAMs are involved in
* To use as references for funding proposals etc.
* To serve as case studies for understanding impact

Not sure the best way to go about this, but as a starter thought I think it would be cool to create a record of all Turing projects that have tangible outputs. Feels like a RAM role above and beyond our specific projects, and focused more on generally engaging with output and implementation across Turing

**Comment by harisood** [comment]
Another starting point could be [here](https://github.com/alan-turing-institute/ASG_RAM/projects?type=classic)

**Comment by aldenc** [comment]
think about best way to capture this - add to strategy epic
