### ISSUE TITLE
Onboarding folder in repo

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/research-application-management#2]
### Summary

* Create onboarding folder with resources for new RAMs

### What needs to be done?

- [ ] Reading Materials 
- [ ] Team Structure Documents
- [ ] People to Meet
- [ ] Trainings to complete
- [ ] Related repos (e.g. https://github.com/alan-turing-institute/asg-community run by @RaoOfPhysics)
- [ ] First few weeks checklist

### Who can help?

* 
* 

---

### Updates

*

**Comment by harisood** [comment]
@dingaaling PR #4 created this folder as a starting point

**Comment by AidaMehonic** [comment]
Adding some old resources:
- RAM Intro Reading: https://hackmd.io/@AidaM/rkCS6a9rK/edit
- TPS Induction Checklist: https://hackmd.io/@turingway/BJAxD3WSt

**Comment by AidaMehonic** [comment]
- add to CRM and provide training

**Comment by harisood** [comment]
First draft of WIP PR available [here](https://github.com/alan-turing-institute/research-application-management/pull/25). Going to do some more work on this this week!

**Comment by harisood** [comment]
@harisood & @dingaaling to cowork on Fri 6th Jan in prep for new starters!

**Comment by dingaaling** [comment]
Notes from Shakir's first weeks:
- https://alan-turing-institute.slack.com/archives/C02KXCLJYP2/p1673970465734449
- "what is REG"
- https://alan-turing-institute.slack.com/archives/C02KXCLJYP2/p1673531202635249

**Comment by harisood** [comment]
Add this somewhere: https://turingcomplete.topdesk.net/tas/public/ssp/content/detail/service?unid=66ac06e58ccf438b8dad20c410ffa129
