### ISSUE TITLE
RAM Turing Way Chapter on OSS Sustainability

### ISSUE THREAD

**Issue by harisood** [alan-turing-institute/research-application-management#23]
### Summary

* An issue to link to progress on our [Turing Way chapter on OSS](https://github.com/alan-turing-institute/the-turing-way/issues/2360) for Bookdash May 2022

### What needs to be done?

See issue for latest updates

### Who can help?

@dingaaling @AidaMehonic @aldenc 

---

### Updates

* 2022-11-18 - @aldenc working on it during RAM coworking

**Comment by dingaaling** [comment]
Potential work stream to investigate/develop this: https://thealanturininstitute-my.sharepoint.com/:w:/g/personal/jding_turing_ac_uk/EVl5IUOootNOn6rMfcNvOHgBkf-vgz7NBymLC1im8aU-Hg?e=gx55Pg

**Comment by dingaaling** [comment]
Chapter started here: https://the-turing-way.netlify.app/collaboration/oss-sustainability/oss-sustainability-challenges.html
