### ISSUE TITLE
Prep for the Turing Lunch & Learn on 1 Feb

### ISSUE THREAD

**Issue by AidaMehonic** [alan-turing-institute/research-application-management#31]
### Prep for the Lunch & Learn session 

Wednesday 1 February, 12:30 – 13:30: Adapting Research Outputs for Real-World Uses 
With Research Application Managers (RAM) Team
 
In this Lunch and Learn, the Research Application Managers (RAM) Team will share best practices for applying your work to real-world problems, whilst ensuring openness and reproducibility.

### What needs to be done?

- [ ] Decide who will give this presentation
- [ ] Prepare the deck
- [ ] Feedback
- [ ] Practice
- [ ] Deliver

### Who can help?

* @aldenc @dingaaling @harisood 

---

**Comment by dingaaling** [comment]
Final product: https://docs.google.com/presentation/d/1ChLuQuyGdGXsc3GPonXRXyMyA1ifm4jC/edit?usp=sharing&ouid=106496390109629319031&rtpof=true&sd=true
