### ISSUE TITLE
Things to work on for book dash May 2023

### ISSUE THREAD

**Issue by aldenc** [alan-turing-institute/research-application-management#35]
please use this issue to add ideas for what we can work on during this upcoming book dash

- Sustainability - HS/CR
- Stakeholder Engagement Resources - SL/JD
- ML models licencing/governance chapter(JD work on this another time/free time)
- Strategy resources - HS
- Workshops (discrete section?) - SL
- Facilitation - JD
- Scriberia sketches
- Ethics: Principle of
- Onboarding - AC
- Cleaning up RAM repo - AC
- Ethics: AI Sustainability (Stakeholder Engagement and Impact Assessments) - CR
- General RAM resource management (repo, contributions, template/resource storage, TTW chapters)
- Engagement with institutions on under-recognised research roles
- PitchFest guidance/resources
- Making workplans/identifying work in hard to define areas (e.g. TRE community - what is success? What does work look like to get there?)

**Comment by harisood** [comment]
Also remember to add the time slots you are able to make!

**Comment by KirstieJane** [comment]
Personally I would LOVE to have something to point to when I talk about the strategy workshops @harisood and David have run for the Data Safe Haven project.

Also, and just to state the obvious, doing one thing as a team is better than starting a bunch of contributions that might be hard to complete after the book dash.

What you pick is up to you all though! Thank you for brainstorming!

How to run PitchFest also a good contribution!

**Comment by harisood** [comment]
Thank you @GeorgiaHCA & @KirstieJane! Will add these to the list above

**Comment by aldenc** [comment]
sessions we're planning to attend together: 
11:00-12:30 Monday May 22
11:30-13:00 Wednesday May 24

**Comment by dingaaling** [comment]
@harisood on Sustainability
- Ideal end goal: Sustainability Framework
- Framework for how to approach this question of sustainability
- Anne's Lit Review
- Case Studies for what we're working on

**Comment by dingaaling** [comment]
## Stakeholder Engagement Best Practices

Goals:
- Aligning/expanding on existing material in TTW
- Capturing RAM expertise and linking to resources

1. Organising effective workshops @S-Laher 
- Inclusivity
- Lit Review Lite for Best Practices (SL)
- Links to resources: Workshop Activity Coordination Spreadsheet (Pre/During/Post)

2. Ethics in Stakeholder Engagement (for impact assessment) @camirincon 

3. Resources for aligning stakeholder interests @dingaaling

**Comment by aldenc** [comment]
hi all, the Monday session had a typo on the index doc - it's 11:00-13:30, so it overlaps our Simon meeting. Thoughts?
a) switch us all to the 8-10:30 session (ugh)
b) cancel Simon meeting (not ideal, but we should check with him if he's free ahead of time anyways)
c) send 1 or 2 reps to the Simon meeting during the session

**Comment by dingaaling** [comment]
JD Plan for Book Dash:
- Monday: RAM teamwork on [Stakeholder Engagement chapter](https://hackmd.io/fsjVhi3dRzeo0veHMsfASg?view) - planning and mapping out a chapter
- Tuesday: [Data Governance for the ML Pipeline](https://docs.google.com/document/d/1PuOzOsvjUf6DfaoCzUnfC73FpelbY40UFTXg2H9huk0/edit#) & any collaboration needed on  [Ethics-informed licensing](https://hackmd.io/FDvRA3ZPRZ-cHlpXHIPLEw?view)
- Wednesday: continue RAM teamwork on Stakeholder Engagement
- Thursday: Data Governance for ML Pipeline & Ethics Informed Licensing

Target outputs:
- Data Governance for the ML Pipeline chapter in PR
- Stakeholder Engagement chapter in PR
- Review new Ethics-informed licensing writing
