### ISSUE TITLE
Add Info about Appraisals to Onboarding and examples of "RAM Objectives"

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/research-application-management#38]
### Summary

* Make sure appraisal/probation info is part of onboarding

### What needs to be done?

- [ ] Add info about appraisals as part of onboarding process with LM
- [ ] @aldenc + @dingaaling  to include examples of general RAM objectives that can be used for probation or appraisals (e.g. year 1 RAM/RAO)
- [ ] Any other RAM/sRAOs who are comfortable sharing example objectives can suggest as well

### Who can help?

* Any RAM or RAO

---

### Updates

*

**Comment by dingaaling** [comment]
AB comment: I try to establish with my team what "hitting this objective" looks like and also, what going above and beyond an objective looks like so there's room to stretch without setting impossible standards

**Comment by dingaaling** [comment]
Notes from RAM meeting 2 June:
    * Timeline for Probation Objectives
    * Timeline for Appraisal
    * Not enough info on it when you join; there is documentation on Mathison, but could use some guidance on what material is relevant/up to date
    * Performance Review a confusing process, can be useful to set expectations on what's to come
    * Guidance could be helpful, not just for RAMs
    * Stick with providing links to Turing guidance + specific examples for RAMs
    * Screenshots - documents could change; maybe just point to the relevant document and general idea of where
    * Document while we go through the process

**Comment by kallewesterling** [comment]
Going through some of the issues in this repo, and found this one. I'd be extremely interested in example objectives from current RAMs, so I'm giving that a +1 here.
