### ISSUE TITLE
Adapt RAM impact matrix w/ Turing 2.0 language

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/research-application-management#53]
### Summary

* See notes in this thread: https://alan-turing-institute.slack.com/archives/C02KXCLJYP2/p1692706500373019

### What needs to be done?

- [ ] Adapt questions for each dimension
- [ ] Update Matrix
- [ ] Update diagrams on repo and website

### Who can help?

* Any RAM interested!

---

### Updates

*

**Comment by aldenc** [comment]
Turing 2.0 version
**Applicability**: Is the research project challenge-driven with potential for real-world use?
**Values**: How much does the team's approach to research align with our focus areas within the TPS programme?
**Practices**: How ready is the team to adopt RAM ways of working?
**Skills**: To what extent does the team have the capability to translate their research to real-world use?

**Comment by aldenc** [comment]
moving to RAM matrix issue
