### ISSUE TITLE
[Discussion]: Project RAM one pager

### ISSUE THREAD

**Issue by harisood** [alan-turing-institute/research-application-management#59]
### Summary

To put together a vision doc or similar for Project RAM

### Detail

The team discussed what work we can undertake together. Part of the difficulty in buying into to Project RAM is knowing exactly what the vision is.

Whilst I think the vision should be collectively created, an initial baseline 'it could look like this' would be helpful (thank you @aranas, @kallewesterling & @f-rower for the discussion.

### Intended Output

One pager soft vision for Project RAM/RAM plan

### Who can help

RAM leadership (@dingaaling, @aldenc), also flagging this as an issue now for me to look at in Nov!

**Comment by aldenc** [comment]
[here](https://github.com/alan-turing-institute/research-application-management/blob/main/docs/project_ram/RAM_1pager.md)
