### ISSUE TITLE
RAM Stakeholder Map Template

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/research-application-management#6]
### Summary

* Create open resource for other ATI projects to use for mapping their stakeholders
* Focus on RAM project needs(e.g. engagement)

### What needs to be done?

- [x] Decide if Miro is the best tool (not free)
- [x] Finalise structure
- [x] Identify additional features to include
- [ ] Create new templates for new features
- [ ] Choose better colour scheme
- [x] Test with RAM team
- [ ] Incorporate feedback from WL testing session

---

### Updates

* Basic Miro template here: https://miro.com/app/board/uXjVPXH3tNw=/?share_link_id=338130463145 (edit mode team link: https://miro.com/welcomeonboard/M1BZSFczRUNONjhPMEJXVzZjdW9pYmRmaTlBeHVzclRVS0VDQTB5cE9OaDQwOFQ3ZzhwY1pieFlSeHY2Z1hma3wzNDU4NzY0NTE0MzgzMjE2MzUw?share_link_id=62706563833)

### Other Examples
* community research for TTW (w/ stakeholder map) is here: https://miro.com/app/board/uXjVODKfyGw=/?share_link_id=174084330478
* open communities map here: https://miro.com/app/board/uXjVONTviD8=/?share_link_id=172270447254
* https://miro.com/app/board/uXjVPcyRAjc=/?share_link_id=466392947694

**Comment by harisood** [comment]
This was tested in a Whitaker Lab meeting in early November, feedback for improvements are here: https://hackmd.io/KescivI_QoSgWCsIdfOkyg

**Comment by dingaaling** [comment]
@harisood has gathered feedback and started using variations of this template in his DSH work
