### ISSUE TITLE
Feedback on 2023-2024 RAM leadership objectives

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/research-application-management#62]
### Summary

@aldenc and @dingaaling have drafted these RAM Leadership objectives for this year - https://hackmd.io/@TuringRAMs/SJsUxt9Wp

The goal is for these to be comprehensive of RAM team priorities/roadmap until May 2024 and cover the critical issues that the RAM team thinks need to happen over the next year. Alden and Jen will be accountable for the delivery, but the entire RAM team will be an active part of the process through things like Project RAM and RAM Day

### What needs to be done?

- [ ] RAM team feedback on objectives
- [ ] Alden and Jen finalise objectives
- [ ] Share final objectives on Github

### Who can help?

* Anyone interested in RAM objectives
---

### Updates

* Some feedback fom @aranas and @f-rower from RAM team meeting 16 Oct https://hackmd.io/fRdv1M3uQcG_c4TFv2vcKw?both

**Comment by kallewesterling** [comment]
@dingaaling in my effort to get started on revising our issue process here on GitHub, I was curious about what the timeline on this issue is?

**Comment by dingaaling** [comment]
Thanks for reviving! I believe Cezanne objectives are due at the end of the month so the deadline is ~30 Nov.  That being said, we can always revise them throughout the year.

**Comment by dingaaling** [comment]
Great find, @kallewesterling guess that is our deadline then :)

**Comment by aldenc** [comment]
objectives submitted, closing issue
