### ISSUE TITLE
Revise enrichment student presentation

### ISSUE THREAD

**Issue by harisood** [alan-turing-institute/research-application-management#63]
### Provide a description

We currently have this intro to RAMs presentation here: https://thealanturininstitute.sharepoint.com/:p:/s/RAM/EW1z9VFovn1Jjhv8jEmEw6UBINr4iAc3fhlDpbKzrTcP6Q?e=71FVt0

I think it lacks a lot of meat and cool stuff that will actually land and be novel content for students.

I scrawled some thoughts down on here: https://hackmd.io/7v4KA8R0SKG7uXDlQ-a8IA

Will have a go at putting together a pres and working with @f-rower about it ahead of Wednesday. Tho anyone who wants to be involved please do!

**Comment by kallewesterling** [comment]
Adding active verb in the title of the issue

**Comment by kallewesterling** [comment]
@harisood what does the `add_to_project` label mean currently in the repo?

**Comment by harisood** [comment]
> Adding active verb in the title of the issue

Like this and immediately adopting

> add_to_project

I think this got added automatically cos I didn't initially add it to a project board but not sure, I think @aldenc set this up so probs knows? I think it can be removed though!

**Comment by aldenc** [comment]
it triggers a workflow to add the issue to our project board
https://github.com/orgs/alan-turing-institute/projects/38

**Comment by f-rower** [comment]
I have written down some feedback on yesterday's presentation slides:

https://hackmd.io/FFMP37XzRGyBdcCstJI40Q

Some highlights:
- Message and structure of presentation needs sharpening for audiences who are unfamiliar with the concept of a RAM, and audiences with high levels of seniority in other organisations
- Show more evidence of thought leadership, especially in the section on impact and sustainability of research
- Need RAM consensus on definition of impact and sustainability of research

**Comment by harisood** [comment]
Thanks @f-rower this feedback is great! 

There's almost two categories of feedback:
- Fundamental things (e.g. how we as a team define impact, sustainability, how the slides are designed)
- Audience specific things (e.g. how would industry respond, how would senior people respond etc.)

I wonder if we need like a core root version that aligns us all on the fundamental things, then we have versions that are slightly adapted to cover the audience specific things

**Comment by f-rower** [comment]
Perhaps we could dedicate some thought to this during tomorrow's coworking?

**Comment by dingaaling** [comment]
@harisood the sharepoint link doesn't currently work for me. Is there another link that we can use to view/edit the latest version of the slides?

**Comment by dingaaling** [comment]
@harisood I believe you mentioned this is finished? If so, could you please add a link to the template in the RAM repo and close this issue?

**Comment by harisood** [comment]
Look at me not closing out issues! 

I restructured the folder here to make a general one that can be adapted, and store this one specifically: https://thealanturininstitute.sharepoint.com/sites/RAM/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FRAM%2FShared%20Documents%2FPresentations%2FTeam%20presentations&viewid=95133367%2D9380%2D40e8%2D9982%2D4094fdadf7ce
