### ISSUE TITLE
Schedule a research methodology collaboration hour (how to do research on Google Scholar, etc.)

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/research-application-management#64]

**Comment by kallewesterling** [comment]
@f-rower adding you here as I think you were the one who spoke to this in our meeting. Not sure if it's something we want to pursue, so feel free to administer (or close) this issue as you see fit :D

**Comment by dingaaling** [comment]
An initial question on this @f-rower or any who have a method for this! Do you have a "place" you go to to store/organise your literature back log?

**Comment by aranas** [comment]
I understand you don't mean a reference manager like mendeley or zotero, where you could in principle create a dedicated folder, but specifically how to have an efficient the back log? I find that my literature backlogs usually become graveyards. I've now started to attach links to readings directly with notes on the project I think they'd be relevant for (in obsidian). This way I am more likely to re-discover a paper in context than going through a daunting list that is growing faster than I can read.

**Comment by dingaaling** [comment]
Thanks for the clarifying qs, @aranas!  Your method sounds great, but do you think it would work as a team resource where our "in context" spaces may be different? Criteria I have in mind are:
- Shared space for RAM team to view/collaboratively take notes on relevant articles
- Organised by different RAM focus areas (e.g. Open Source sustainability, participatory methods)
- (And I really like your point of) some structure enabling rediscovery (avoiding long list)

For example, I quite like what Ruth did with the [clim-recal lit review](https://docs.google.com/spreadsheets/d/1AFyRn7LoriXMvdrbVF_OaYh4kMud1ghVphG4EXMhY20/edit?usp=sharing), but Google Sheets it is essentially a long list as well

**Comment by dingaaling** [comment]
Scheduled for 19 January 10AM
