### ISSUE TITLE
Involve the RAM programme (and TPS broadly) in open-source RSE/REG drop-in sessions

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/research-application-management#65]
Original post in `tps` here: https://alan-turing-institute.slack.com/archives/CH2TBRUQH/p1700061506190049

**Comment by kallewesterling** [comment]
https://alan-turing-institute.slack.com/archives/CGWHGS9FS/p1701092893525919

**Comment by dingaaling** [comment]
I've caught up with Fede, Iain, Ryan, and Emma on this via Slack. Here are some blurbs from our convo. Currently we're exploring how to put this conversation in a more open/public space so we can continue the discussions with the wider TPS team

Emma: I've chatted with the community manager team and we are happy to go forward with support for the drop in sessions. A few suggestions are:
 - Could we approach this as TPS help and then we can recruit people and their skills across TPS - we are more than RAM and RCM teams so we want more people to be involved. - spread the load a bit!
- We don't have much capacity so could not be there at every session - would be happy to be on some sort of TPS rotating schedule of experts. - the person that represents TPS could advertise their skills before the session but also act as a connector to other TPS people for other skills.
 - How do you feel about opening this up beyond Turing? Could we advertise to Turing related projects? or even more openly?

Jen:
* To promote the range of skills, for these sessions, could we potentially find another name (e.g. "open science brainstorming")
 - Could I suggest we all touch base in early 2024 instead as we'll likely need to touch base again anyway?

Fede: This all sounds great and very much in line with what we had in mind. We plan to start this from the new year, so no problem and we also thought about whether to go beyond Turing.  We were also looking for a better name and I think "{ something } brainstorming" would capture the essence of what we all want to do
* We were thinking that maybe a first step to go beyond Turing could be to reach out to the Turing Fellow networks and support their respective groups, but we can discuss about this all together in January
* From the REG side, we plan to run a pilot between Jan and June (with maybe a touchbase in April) to see how it generally goes and what's the demand
* we have a hackmd where we were capturing ideas - we can share this later today

TPS side next steps:
* Jen/Emma: Propose this as a topic for a tps team meeting in January
* Jen/Jim: Raise as part of tps-delivery meeting in 2024
* RAMs: decide what skills/topics we can contribute

**Comment by dingaaling** [comment]
closing this as it is replaced by #71
