### ISSUE TITLE
RAM contributions to REG Drop-in Sessions

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/research-application-management#71]
### Provide a description

Identify how RAMs can collaborate with REG/contribute to [REG drop-in sessions](https://github.com/alan-turing-institute/research-engineering-group/wiki/Drop%E2%80%90in-Sessions); some other info in #65 

There is a #core-capabilities-drop-in channel on slack if you'd like to join in the conversation. It's private but @aranas and @dingaaling can add you in in the interim

**Comment by dingaaling** [comment]
Notes from 10 Jan meeting:
- Good opportunity to showcase and make available Turing's core capabilities 
- Decision points: frequency, timing, what kinds of capabilities to provide
- Luis: Challenge in Turing with info overload; how best to promote to new people (and current)?
- Emma: Office hours are intimidating for people so low numbers may be an ongoing challenge; Turing (or RIR) Collaboration Cafe to create space for cross-GC conversations
- Fede: we do have a lot of informal meetings, aredirecting adhoc requests "why don't you come to my office hours"
- Iain: people who do drop in often become regulars, so it's maybe more addressing the challenge of friction at the beginning of not knowing what to expect
- Sophie: can we connect drop ins with other activities like technical talks or workshops; perhaps making sessions themed can make clear what capabilities are available at each session
- How to best advertise? Present at Town Hall, Induction for new starters, Big Screen, in-person sessions
- REG, TPS (RAM/RCM), Data Wrangling

## Next Steps
- REG running every Tues or Wed for next 6 months
- We can explore the right cadence for the other teams (e.g. once a month?) to join in; make sure to give them at least one week heads up

**Comment by aranas** [comment]
also, let's help reg to revive the interest in regular weekly drop-in sessions by sharing their info across the teams we work:
e.g. [pass on their handbook](https://alan-turing-institute.github.io/REG-handbook/docs/regular_events/drop-in_sessions/)

for us internally, a next step might also be to list for everyone in the RAM team their "specialty" as well as shared resources or strategies to advise people

**Comment by dingaaling** [comment]
Agree @aranas that it would be good for us to share our individual expertise, but I do think it is important for us to also think about what the RAM "core capabilities" are that our team can offer.

This will require us to further define, document, and templatise an offering though.
