### ISSUE TITLE
RAM documentation day

### ISSUE THREAD

**Issue by aldenc** [alan-turing-institute/research-application-management#72]
Let's plan another RAM day, this time to work our way through some documentation! Some proposed dates:
Monday, February 5th
Monday, February 26th
Tuesday, February 27th
Friday, March 1
Monday, March 4
Thursday, March 7th
Friday, March 8th

**Comment by aranas** [comment]
all of those work for me

**Comment by S-Laher** [comment]
Please no Friday as long as we can help it - I prefer tue 27th feb & Thurs 7th Mar - The mondays also work it just means I have to miss many of my weekly project meetings

**Comment by harisood** [comment]
26th, 27th, 4th work best for me

**Comment by dingaaling** [comment]
Days that work for me:
- 27 Feb
- 1 March
- 4 March
- 7 March

**Comment by aldenc** [comment]
@kallewesterling @f-rower does 27th Feb work for you?

**Comment by f-rower** [comment]
@aldenc 27th works for me!

**Comment by dingaaling** [comment]
Invites sent today for RAM day on 27 Feb
