### ISSUE TITLE
RAM Documentation Day Planning

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/research-application-management#73]
### Summary

RAM Documentation Day is on 27 Feb with 3 sessions
* 9-11
* 11-12
* 13-17

### What needs to be done?

- [ ] Suggest topics for documentation
- [ ] Identify facilitators for each topic
- [ ] Identify target outcomes of the day

### Who can help?

* All RAMs
---

### Updates

*

**Comment by dingaaling** [comment]
Suggestions:
- Pre-workshop stakeholder engagement, capture experiences from CSIRO (@dingaaling + @aranas )
- Panel preparation best practices (@aranas)
- Workshop facilitation (@aranas + @harisood)
- Applications of the RAM matrix (@f-rower)
- RAM + Partnerships ways of working (@dingaaling + @f-rower)

**Comment by harisood** [comment]
I could revisit the strategy stuff, also governance/website building stuff - could e.g. create a template way to set up an accessible site for projects using Hugo which others could reuse

**Comment by dingaaling** [comment]
My top choices to work on:
3. Pre and post-stakeholder workshop work, eg could update [stakeholder workshop checklist](https://github.com/alan-turing-institute/research-application-management/blob/main/docs/stakeholder_workshops.md)
- Hope to work on this with @aranas to capture CSIRO work
4. Write up workshop facilitation best practices
- Hope to work on this with @harisood 
7. Write up RAM + Partnerships ways of working
- Hope to work on this with @f-rower to capture our work with Xander/Mark

**Comment by f-rower** [comment]
https://github.com/alan-turing-institute/research-application-management/issues/73#issuecomment-1956372561
@harisood wonder if we could join forces on this? I started a [guide for ADViCE](https://hackmd.io/1rOVdqk0RzOseN-Dj9pr4A) on how to contribute to the [ADViCE site](https://alan-turing-institute.github.io/ADViCE/) (although I did use a Hugo theme rather than coding from scratch)

**Comment by f-rower** [comment]
@aldenc I would add to my to-do list turning my RAM project prioritisation framework into a template

So my priorities for the day would be the following:

- Write up RAM + Partnerships ways of working with @dingaaling 
- XX. [Create list of 2024 conferences of interest to RAMs](https://github.com/orgs/alan-turing-institute/projects/38/views/2?pane=issue&itemId=45547596)
- XXI. Finalise RAM Project Prioritisation framework template
- Contribute more RAM papers/research resources - things we should all be collectively reading to get better at our jobs with @harisood

**Comment by S-Laher** [comment]
> Suggested items for Tuesday:
> 
> 1. [Update strategy templates](https://github.com/orgs/alan-turing-institute/projects/38/views/2?pane=issue&itemId=29501528)
> 2. Create checklist for panel preparation, similar to [events checklist](https://github.com/alan-turing-institute/research-application-management/blob/main/docs/events.md)
> 3. Capture pre-stakeholder workshop learnings, eg could update [stakeholder workshop checklist](https://github.com/alan-turing-institute/research-application-management/blob/main/docs/stakeholder_workshops.md)
> 4. Write up workshop facilitation guidelines
> 5. Write up RAM resources page
> 6. Write up applications of RAM matrix
> 7. Write up RAM + Partnerships ways of working
> 8. Clean up repo organization and update [readme](https://github.com/orgs/alan-turing-institute/projects/38/views/2?pane=issue&itemId=45547541)
> 9. Review project board and update/close issues
> 10. [Create list of 2024 conferences of interest to RAMs](https://github.com/orgs/alan-turing-institute/projects/38/views/2?pane=issue&itemId=45547596)
> 
> Please reply to this issue indicating your top choices or suggesting other tasks you'd like to complete

I would like to work on 

- 1 I am keen to work on strategy 
- 3
- 4

One suggestion - the day does seem task heavy which is great as we get things done, however I would have liked later in the day to have discussed RAM team-level topics such as but not limited to as, our priorities, fundamental challenges, workload, team research opportunities/collaboration, team strategy ....

**Comment by aranas** [comment]
Great list of tasks! 
My priorities will be
- Pre and post-stakeholder workshop work (to reflect on CSIRO workshop with @dingaaling )
- Rework events checklist to include panel-specific prep and add reflections on Melbourne panel experience to @kallewesterling's panel discussion [summary doc](https://hackmd.io/-ZLXJ6C-QhCS7je0xsSvow), then move that to RAM repo.

**Comment by dingaaling** [comment]
Thanks for that suggestion @S-Laher! 

I believe Alden had a different vision/focus in mind for this RAM Documentation Day to be more focused on finishing specific tasks. @aldenc  - perhaps you could open the day by sharing that vision with the team so we can start the day on the same page for what the focus of the day will be?

Noted that you are interested in a strategy day though Shakir. Perhaps a good one to do with Aida as she ramps back into work.

**Comment by harisood** [comment]
Looks like there's a bunch of stuff I can do! Flexible on Priority but thinking:

- Project strategy stuff (with @S-Laher if interested)
- Website stuff + RAM research (with @f-rower )
- Workshop facilitation (with @dingaaling )
- RAM matrix (if time)

**Comment by S-Laher** [comment]
@aldenc @dingaaling - sorry i remember now this day had a 'lets get task done' focus 
we can pick up team strategy another day

@harisood i am very keen on working with you on this - i have been doing a bunch of stuff for some research work which has felt a little disjointed e.g., governance structures, outcomes, outputs, metrics all linked to a research strategy
Would be nice to bring it all togther into a framework which eventually leads to a concrete methodology
