### ISSUE TITLE
website text updates

### ISSUE THREAD

**Issue by aldenc** [alan-turing-institute/research-application-management#81]
we've been updated to the "new" version (from 6 months ago) - let's use this issue to capture any small changes that we can make before AIUK (pending a possible future overhaul)

- remove Cami
- add ADVICE
- update matrix language
- update links (bottom section)

pleases share up-to-date links and add any other changes you'd like to see

**Comment by dingaaling** [comment]
I'd also suggest changing `Practices: How ready are the team to adopt RAM ways of working?` to `Practices: How ready are the team to adopt open ways of working?`

**Comment by S-Laher** [comment]
Some wording for our website of RAM involvement in projects:-

- Development and validation of an existing open-source platform, known as the Trustworthy and Ethical Assurance (TEA) Platform(https://github.com/alan-turing-institute/AssurancePlatform), which has been designed by researchers at the Alan Turing Institute and the University of York to help users to create assurance arguments. TEA is being applied in the context of Digital Twins and Digital Healthcare. Please see TEA-DT(https://www.turing.ac.uk/research/research-projects/trustworthy-and-ethical-assurance-digital-twins-tea-dt) and TEA-DH (https://www.turing.ac.uk/research/research-projects/trustworthy-and-ethical-assurance-digital-healthcare).

- Delivering activities and research on AI governance, regulation and standards by leveraging expertise from the AI Governance and Regulatory Innovation team(https://www.turing.ac.uk/research/research-programmes/public-policy/public-policy-themes/ai-regulation-and-standards) and the AI Standards Hub(https://aistandardshub.org/).

- Supporting the AI for Decarbonisation Virtual Centre of Excellence (ADViCE)(https://www.turing.ac.uk/research/research-projects/advice) to deliver on its wider ambitions to coordinate and engage stakeholders across high-emitting sectors, foster cross-sector collaboration and develop innovative AI technologies for decarbonisation applications to support the transition to Net Zero.

**Comment by dingaaling** [comment]
Language to update Matrix here in [RAM Project Engagement Prioritisation](https://thealanturininstitute-my.sharepoint.com/:w:/r/personal/fgomezmedina_turing_ac_uk/Documents/RAM%20Project%20Prioritisation%20Template.docx?d=w5d76cb00cf2f46118101cb0ad16aaa38&csf=1&web=1&e=CzWdcF)

**Comment by dingaaling** [comment]
closing as this is now live!
